# frozen_string_literal: true

# Configures Active Record Encryption using keys stored in ~/.anima/config/encryption.key.
# Keys are generated by the installer and loaded on every boot.
#
# @see Anima::EncryptionKeys
# @see https://guides.rubyonrails.org/active_record_encryption.html
require_relative "../../lib/anima/encryption_keys"

keys = Anima::EncryptionKeys.load_or_generate

Rails.application.configure do
  config.active_record.encryption.primary_key = keys[:primary_key]
  config.active_record.encryption.deterministic_key = keys[:deterministic_key]
  config.active_record.encryption.key_derivation_salt = keys[:key_derivation_salt]
end
