<% anima_home = File.expand_path("~/.anima") %>

default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  timeout: 5000
  schema_format: sql

development:
  primary:
    <<: *default
    database: <%= File.join(anima_home, "db", "development.sqlite3") %>
  queue:
    <<: *default
    database: <%= File.join(anima_home, "db", "development_queue.sqlite3") %>
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: <%= File.join(anima_home, "db", "development_cable.sqlite3") %>
    migrations_paths: db/cable_migrate

test:
  primary:
    <<: *default
    database: <%= File.join(anima_home, "db", "test.sqlite3") %>
  queue:
    <<: *default
    database: <%= File.join(anima_home, "db", "test_queue.sqlite3") %>
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: <%= File.join(anima_home, "db", "test_cable.sqlite3") %>
    migrations_paths: db/cable_migrate

production:
  primary:
    <<: *default
    database: <%= File.join(anima_home, "db", "production.sqlite3") %>
  queue:
    <<: *default
    database: <%= File.join(anima_home, "db", "production_queue.sqlite3") %>
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: <%= File.join(anima_home, "db", "production_cable.sqlite3") %>
    migrations_paths: db/cable_migrate
