# frozen_string_literal: true

# A persisted summary of conversation context created by Mneme before
# events evict from the viewport. Snapshots capture the "gist" of what
# happened so the agent retains awareness of past context.
#
# Level 1 snapshots are created from raw events (messages + thinks).
# Higher levels (future slices) compress lower-level snapshots.
#
# @!attribute text
#   @return [String] the summary text generated by Mneme
# @!attribute from_event_id
#   @return [Integer] first event ID covered by this snapshot
# @!attribute to_event_id
#   @return [Integer] last event ID covered by this snapshot
# @!attribute level
#   @return [Integer] compression level (1 = from raw events)
# @!attribute token_count
#   @return [Integer] cached token count of the summary text
class Snapshot < ApplicationRecord
  belongs_to :session

  validates :text, presence: true
  validates :from_event_id, presence: true
  validates :to_event_id, presence: true
  validates :level, presence: true, numericality: {greater_than: 0}

  scope :for_level, ->(level) { where(level: level) }
  scope :chronological, -> { order(:from_event_id) }
end
